CREATE QUEUE [dbo].[ObjectChangeLogDDL_BrokerQueue]
WITH STATUS=ON,
RETENTION=OFF,
POISON_MESSAGE_HANDLING (STATUS=ON),
ACTIVATION (
STATUS=ON,
PROCEDURE_NAME=[dbo].[spu_ObjectChangeLogDDL],
MAX_QUEUE_READERS=2,
EXECUTE AS OWNER
)
ON [PRIMARY]
GO
